version: '3'
services:
  eva-smarthome-server:
    container_name: eva_smarthome_server
    hostname: smarthomesrv
    ports:
      - "8828:8828"
    environment:
      - auto_install=1
      - mqtt=
      - link=1
      - product=all
      - layout=enterprise
      - MASTERKEY=demo123
      - DEFAULTKEY=demo-default
      - OPKEY=
      - OPPASSWD=123
      - cloud_manager=1
      - deploy=
      - download=
      - debug=
    image: altertech/eva-ics
    volumes:
        - ./ui:/ui
        - ./data:/data
        - ./cfg:/deploy-cfg
    networks:
      eva_smarthome_ic:
        ipv4_address: 10.27.14.199

networks:
  eva_smarthome_ic:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.27.14.0/24

volumes:
  ui:
  cfg:
