version: '3'
services:
  eva-smarthome-server:
    image: altertech/eva-ics:3.4.0-2021070902-32
    container_name: eva_smarthome_server
    hostname: smarthomesrv
    ports:
      - "8828:8828"
    environment:
      - MASTERKEY=demo123
      - DEFAULTKEY=default123
      - DEPLOY=https://raw.githubusercontent.com/alttch/eva-demo-smarthome/master/deploy/smarthome-demo.yml
    networks:
      eva_smarthome_ic:
        ipv4_address: 10.27.14.199
    volumes:
      - ./ui:/mnt/ui

networks:
  eva_smarthome_ic:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.27.14.0/24

volumes:
  ui:
