url: https://eva.lab.altt.ch:38848
class: dashboard

buttons:
  alarm:
    icon: attn
    item: lvar:security/alarm
    title: Alarm
  cctv:
    icon: cam
    item: unit:equipment/cctv
  vent:
    icon: vent
    item: unit:equipment/vent

  light_room1:
    icon: lamp
    item: unit:light/room1
    title: Room 1
  light_room2:
    icon: lamp
    item: unit:light/room2
    title: Room 2
  light_hall:
    icon: lamp
    item: unit:light/hall
    title: Hall
  window_room1:
    icon: window_left
    item: unit:windows/room1
    menu: 3
  window_room2:
    icon: window_right
    item: unit:windows/room2
    menu: 3

  lights_on:
    icon: lamps.s_1
    item: lmacro:control/lights_on
  lights_off:
    icon: lamps.s_0
    item: lmacro:control/lights_off

  thermo_room1_off:
    icon: thermostat.s_0
    title: Turn off
    action: unit:thermo/room1
    action_params:
      s: 0
  thermo_room1_15:
    icon: thermostat.s_1
    action: unit:thermo/room1
    title: "Set 15&#8451;"
    action_params:
      s: 1
      v: 15
  thermo_room1_20:
    icon: thermostat.s_1
    action: unit:thermo/room1
    title: "Set 20&#8451;"
    action_params:
      s: 1
      v: 20
  thermo_room1_25:
    icon: thermostat.s_1
    action: unit:thermo/room1
    title: "Set 25&#8451;"
    action_params:
      s: 1
      v: 25
  thermo_room1:
    icon: thermostat
    item: unit:thermo/room1
    value: "&#8451;"
    title: profiles
    menu:
      - thermo_room1_off
      - thermo_room1_15
      - thermo_room1_20
      - thermo_room1_25
  thermo_room2:
    icon: thermostat
    item: unit:thermo/room2
    value: "&#8451;"
    title: slider
    slider:
      min: 15
      max: 25
      step: 1

  open_windows:
    icon: windows.s_1
    item: lmacro:control/open_windows
  close_windows:
    icon: windows.s_0
    item: lmacro:control/close_windows

  day_mode:
    icon: sun.s_1
    item: lmacro:profiles/day_mode
  winterday_mode:
    icon: snow.s_1
    item: lmacro:profiles/winterday_mode
  night_mode:
    icon: moon.s_1
    item: lmacro:profiles/night_mode

  enter:
    icon: enter.s_1
    item: lmacro:control/enter
  exit:
    icon: stop.s_1
    item: lmacro:control/exit


data:
  temp1_int:
    icon: indoor_temp
    item: sensor:env/temp1_int
    u: "&#8451;"
    decimals: 0
  hum1_int:
    icon: indoor_hum
    item: sensor:env/hum1_int
    u: "%"
    decimals: 0
  temp2_int:
    icon: indoor_temp
    item: sensor:env/temp2_int
    u: "&#8451;"
    decimals: 0
  hum2_int:
    icon: indoor_hum
    item: sensor:env/hum2_int
    u: "%"
    decimals: 0
  temp_ext:
    icon: outdoor_temp
    item: sensor:env/temp_ext
    u: "&#8451;"
    decimals: 0
  hum_ext:
    icon: outdoor_hum
    item: sensor:env/hum_ext
    u: "%"
    decimals: 0
  pressure:
    icon: pressure
    item: sensor:env/air_pressure
    u: " hPa"
    decimals: 0

data-blocks:
  1:
    elements:
      - temp1_int
      - hum1_int
  2:
    elements:
      - temp2_int
      - hum2_int
  3:
    elements:
      - temp_ext
      - hum_ext
      - pressure

 
control-blocks:
  1:
    elements:
      - light_room1
      - window_room1
      - thermo_room1
  2:
    elements:
      - light_room2
      - window_room2
      - thermo_room2
  3:
    elements:
      - light_hall
      - alarm
      - cctv
      - vent
  4:
    elements:
      - lights_on
      - lights_off
      - open_windows
      - close_windows
  5:
    elements:
      - day_mode
      - winterday_mode
      - night_mode
  6:
    elements:
      - enter
      - exit
layout:
  bar1:
    control-blocks:
      - 1
      - 4
    data-block: 1
  bar2:
    control-blocks:
      - 2
      - 5
    data-block: 2
  bar3:
    control-blocks:
      - 3
      - 6
    data-block: 3
    sys-block: true

