#url: https://my.external.domain:port/
class: simple

buttons:
  light_room2:
    icon: lamp
    item: unit:light/room2
    title: Room 1
  window_room2:
    icon: window_right
    item: unit:windows/room2
    menu: 3
  thermo_room2:
    icon: thermostat
    item: unit:thermo/room2
    value: "°C"
    title: slider
    slider:
      min: 15
      max: 25
      step: 1
      can_off: true

cameras:
  room2:
    image: /rpvt?f=127.0.0.1:8118/cam/2?nocache=$NOCACHE

layout:
  camera:
    id: room2
    reload: 1
    action: url:/ui/
  buttons:
    - light_room2
    - window_room2
    - thermo_room2
  #sysblock: true
