#url: https://my.external.domain:port/
class: sensors

charts:
  room1_temp:
    icon: indoor_temp
    item: sensor:env/temp1_int
    title: Room 1 temperature
    cfg: default
    units: "°C"
    color: orange
    fill: "start"
    background-color: rgba(255, 125 ,0, 0.8)
    decimals: 0
    params:
      timeframe: 1D
      fill: 30T:1
      prop: value

  room1_hum:
    icon: indoor_hum
    item: sensor:env/hum1_int
    title: Room 1 humidity
    cfg: default
    units: "%"
    color: '#225588'
    fill: "start"
    decimals: 0
    background-color: rgba(17, 51, 85, 0.8)
    params:
      timeframe: 1D
      fill: 30T:1
      prop: value

  room2_temp:
    icon: indoor_temp
    item: sensor:env/temp2_int
    title: Room 2 temperature
    cfg: default
    units: "°C"
    color: orange
    fill: "start"
    background-color: rgba(255, 125 ,0, 0.8)
    decimals: 0
    params:
      timeframe: 1D
      fill: 30T:1
      prop: value

  room2_hum:
    icon: indoor_hum
    item: sensor:env/hum2_int
    title: Room 2 humidity
    cfg: default
    units: "%"
    color: '#225588'
    fill: "start"
    decimals: 0
    background-color: rgba(17, 51, 85, 0.8)
    params:
      timeframe: 1D
      fill: 30T:1
      prop: value

  outdoor_temp:
    icon: outdoor_temp
    item: sensor:env/temp_ext
    title: Outdoor temperature
    cfg: default
    units: "°C"
    color: orange
    background-color: rgba(255, 125 ,0, 0.5)
    decimals: 0
    params:
      timeframe: 1D
      fill: 30T:1
      prop: value

  outdoor_hum:
    icon: outdoor_hum
    item: sensor:env/hum_ext
    title: Outdoor humidity
    cfg: default
    units: "%"
    color: '#8899aa'
    fill: "start"
    decimals: 0
    background-color: rgba(51, 102, 153, 0.8)
    params:
      timeframe: 1D
      fill: 30T:1
      prop: value

  air_pressure:
    icon: outdoor_pressure
    title: Air pressure
    item: sensor:env/air_pressure
    cfg: default
    units: " hPa"
    color: red
    background-color: rgba(210, 77, 87, 0.7)
    decimals: 0
    params:
      timeframe: 1D
      fill: 30T:1
      prop: value

layout:
  charts:
    - { id: room1_temp, reload: 180 }
    - { id: room1_hum, reload: 180 }
    - { id: room2_temp, reload: 180 }
    - { id: room2_hum, reload: 180 }
    - { id: outdoor_temp, reload: 180 }
    - { id: outdoor_hum, reload: 180 }
    - { id: air_pressure, reload: 180 }
  #sys-block: true
